InsuranceOffer.Test.Case.UI/Models/ErrorViewModel.cs
using System;

namespace InsuranceOffer.Test.Case.UI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

InsuranceOffer.Test.Case.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using InsuranceOffer.Test.Case.UI.Models;

namespace InsuranceOffer.Test.Case.UI.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

InsuranceOffer.Test.Case.UI/Controllers/TeklifAlController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using InsuranceOffer.Test.Case.DataLayer.Model;
using InsuranceOffer.Test.Case.DataLayer.Repository;
using InsuranceOffer.Test.Case.UI.Business;
using InsuranceOffer.Test.Case.UI.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;

namespace InsuranceOffer.Test.Case.UI.Controllers
{
    public class TeklifAlController : Controller
    {
        private readonly IDataRepository<CustomerInfo> _customerInfoRepository;
        private readonly IDataRepository<CustomerInsuranceOffers> _customerInsuranceOffersDataRepo;
        IConfiguration _configuration;
        public TeklifAlController(IDataRepository<CustomerInfo> customerInfoRepository, IConfiguration configuration, IDataRepository<CustomerInsuranceOffers> customerInsuranceOffersDataRepo)
        {
            _customerInfoRepository = customerInfoRepository;
            _configuration = configuration;
            _customerInsuranceOffersDataRepo = customerInsuranceOffersDataRepo;
        }
        public IActionResult Index()
        {
            CustomerInfo model = new CustomerInfo();
            return View(model);
        }
        public IActionResult AllOffers(CustomerInfo model)
        {
            var jsonRequest = JsonConvert.SerializeObject(model);
            TeklifHesapla teklifHesapla = new TeklifHesapla(_configuration);
            if (model.ID == 0)
            {
                var result = _customerInfoRepository.Create(model);
                var response = teklifHesapla.TeklifGetir(jsonRequest);
                var customerInsuranceOffers = JsonConvert.DeserializeObject<List<CustomerInsuranceOffers>>(response);
                foreach (var item in customerInsuranceOffers)
                {
                    item.CustomerID = result.ID;
                    _customerInsuranceOffersDataRepo.Create(item);
                };

                return View(customerInsuranceOffers);
            }
            else
            {
                var customer = _customerInfoRepository.GetByTckn(model.TCKN);
                var custInsuranceOffer = _customerInsuranceOffersDataRepo.GetOffersByCustomerID(customer.ID);

                return View(custInsuranceOffer);
            }
        }
        [HttpGet]
        public ActionResult GetCustomerInfo(string tckn, string plaka)
        {
            var result = _customerInfoRepository.GetAll().Where(x => x.TCKN == tckn && x.Plaka == plaka).FirstOrDefault();
            //var result = _dataRepository.GetAsQueryable(x => x.TCKN == tckn && x.Plaka == plaka);
            return Json(result);
            // Do some work and return View()
        }

        public ActionResult GetAllOffersByTckn()
        {
            return View();
        }
        [HttpPost]
        public ActionResult GetAllOffersByTcknForCustomer(string tckn)
        {
            var customer = _customerInfoRepository.GetByTckn(tckn);
            if (customer!=null)
            {

                var custInsuranceOffer = _customerInsuranceOffersDataRepo.GetOffersByCustomerID(customer.ID);
                return View("AllOffers", custInsuranceOffer);
            }
            return View("CustomerNotFound");
        }
    }
}

InsuranceOffer.Test.Case.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Sigorta Teklif Hesaplama</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

InsuranceOffer.Test.Case.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InsuranceOffer.Test.Case.UI</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TeklifAl" asp-action="Index">Teklif Hesapla</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TeklifAl" asp-action="GetAllOffersByTckn">TCKN ile Teklifleri Getir</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - InsuranceOffer.Test.Case.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

InsuranceOffer.Test.Case.UI/Views/TeklifAl/AllOffers.cshtml
@model List<InsuranceOffer.Test.Case.DataLayer.Model.CustomerInsuranceOffers>



    <div><b>Telkif Listesi</b><br /></div>
    <table class="table table-bordered table-responsive table-hover">
        <tr>
            <th>Firma Adı </th>
            <th>Firma Logosu </th>
            <th>Teklif Açıklaması </th>
            <th>Teklif Tutarı</th>
            <th>plaka</th>
        </tr>
        @foreach (var d in Model)
        {
            <tr>
                <td>@d.FirmaAdi</td>
                <td>@d.FirmaLogosu</td>
                <td>@d.TeklifAciklamasi</td>
                <td>@d.TeklifTutari</td>
                <td>@d.Plaka</td>

            </tr>
        }
    </table>

InsuranceOffer.Test.Case.UI/Views/TeklifAl/CustomerNotFound.cshtml
@{
    ViewData["Title"] = "CustomerNotFound";
}

<h1>Bu TCKN'ye ait teklif bulunamadı</h1>

InsuranceOffer.Test.Case.UI/Views/TeklifAl/GetAllOffersByTckn.cshtml
<head>
    <script src="~/js/jquery-3.4.1.min.js"></script>
</head>
<div class="tab-content">
    <div class="tab-pane active" id="tab_0">
        <div class="portlet box green">
            <div class="portlet-title">
                <h1 class="caption">
                    <i class="fa fa-gift"></i>Tekliflerimi Listele
                </h1>
                <div class="tools">
                    <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                    <a href="#portlet-config" data-toggle="modal" class="config" data-original-title="" title=""> </a>
                    <a href="javascript:;" class="reload" data-original-title="" title=""> </a>
                    <a href="javascript:;" class="remove" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body form">
                <form id="getAllOffers" method="post" action="GetAllOffersByTcknForCustomer" class="form-horizontal">
                    <dsiv class="form-body">
                        <div class="form-group">
                            <label class="col-md-3 control-label">TC Kimlik Numarası</label>
                            <div class="col-md-4">
                                <input class="form-control" placeholder="TCKN" name="tckn" id="tckn">
                            </div>
                        </div>
                    </dsiv>
                    <div class="form-actions">
                        <div class="row">
                            <div class="col-md-offset-3 col-md-9">
                                <button type="submit" class="btn green"><i class="fa fa-check"></i> Teklifleri Getir</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

InsuranceOffer.Test.Case.UI/Views/TeklifAl/Index.cshtml
@model InsuranceOffer.Test.Case.DataLayer.Model.CustomerInfo
<head>
    <script src="~/js/jquery-3.4.1.min.js"></script>
</head>
<div class="tab-content">
    <div class="tab-pane active" id="tab_0">
        <div class="portlet box green">
            <div class="portlet-body form">
                <!-- BEGIN FORM-->
                <form  method="post" action="TeklifAl/AllOffers" class="form-horizontal">
                    <input asp-for="@Model.ID" type="hidden" id="custID" />
                    <div class="form-body">
                        <div class="form-group">
                            <label class="col-md-3 control-label">TC Kimlik Numarası</label>
                            <div class="col-md-4">
                                <input asp-for="@Model.TCKN" class="form-control" placeholder="TCKN" id="tckn">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">Plaka</label>
                            <div class="col-md-4">
                                <input asp-for="@Model.Plaka" class="form-control" placeholder="Plaka" id="plaka">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">Ruhsat Seri Kodu</label>
                            <div class="col-md-4">
                                <input asp-for="@Model.RuhsatSeriKodu" class="form-control" placeholder="Ruhsat Seri Kodu" id="ruhsatKodu">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">Ruhsat Seri No</label>
                            <div class="col-md-4">
                                <input asp-for="@Model.RuhsatSeriNo" class="form-control" placeholder="Ruhsat Seri No" id="ruhsatSeriNo">
                            </div>
                        </div>
                    </div>
                    <div class="form-actions">
                        <div class="row">
                            <div class="col-md-offset-3 col-md-9">
                                <button id="updateAjax" class="btn green"><i class="fa fa-check"></i>Teklifleri Göster</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var field = document.getElementById('ruhsatKodu');

    field.onmouseup = function () {
        var tckn = document.getElementById("tckn").value;
        var plaka = document.getElementById('plaka').value;
        $.ajax({
            type: 'GET',
            url: '/TeklifAl/GetCustomerInfo',
            data: { tckn: tckn, plaka: plaka },
            contentType: "application/json",
            success: function (result) {
                if (result != null) {
                    console.log(result);
                    console.log(result.ruhsatSeriNo);
                    document.getElementById('ruhsatKodu').value = result.ruhsatSeriKodu;
                    document.getElementById('ruhsatSeriNo').value = result.ruhsatSeriNo;
                    document.getElementById('custID').value = result.id;
                }
            }
        });
    }
</script>